### ISSUE TITLE
is the Docker image at nearup/nearprotocol, or nearprotocol/nearup? (possible namespace hack?)

### ISSUE THREAD

**Issue by myklemykle** [near/node-docs#58]
Hi,

The docs for nearup at https://github.com/near/nearup give the Docker address: nearprotocol/nearup .
But the docs in this repo are give another address, that looks similar but is actually different: nearup/nearprotocol .

I'm sorry I can't figure out how to check if these are signed by any valid NEAR person ... 
The nearprotocol/* namespace in Docker Hub looks pretty realistic; there's a bunch of images there, they're all what I'd expect ... 
The nearup/* namespace in Docker Hub, I can't really see any info, but there is just one image there.  It has different version numbers from nearprotocol/nearup.  It looks kinda sketchy. But this is the image that the doc is currently pointing at.

Is there some intentional reason why this doc is pointing people to use the nearup Docker image "nearup/nearprotocol" instead of "nearprotocol/nearup"  Or is that a bug?

**Comment by DDeAlmeida** [comment]
Hello,

The latest version is on nearup/nearprotocol.

As NearUp is now down, we don't recommand to us nearup.
Please use nearcore.
