### ISSUE TITLE
[DOC] Compilation prerequisite is missing and document is not easy to find for validators

### ISSUE THREAD

**Issue by ailisp** [near/node-docs#9]
***Is your feature request related to a problem? Please describe.***

*   [https://docs.near.org/docs/contribution/nearcore#compile-from-source](https://docs.near.org/docs/contribution/nearcore#compile-from-source) is incomplete for not including apt-get dependencies
*   Validators are not easy to find out this documentation if they want to compile their own node.

***Describe the solution you'd like***

*   apt-get dependencies (or brew, on Mac) should be documented
*   Would be nice to link this document in validator page, so they can find it
*   Address it's important to git clone nearcore source code instead of downloading because it's required for compilation process.

***Additional context***

**Comment by nikurt** [comment]
@ailisp, Which dependencies are missing and on which platforms?
This page has `apt-get install` commands that have been working fine for me:
https://near-nodes.io/validator/running-a-node#compiling-and-running-a-node-without-docker

**Comment by ailisp** [comment]
@nikurt you are right. I think all my said has been addressed in current doc. Maybe worth mention a step to install rust, which is missing.

**Comment by nikurt** [comment]
Documentation has 6 copies of the command `apt install <a list of dependencies>` on 5 different pages. That needs to be cleaned up as well.

```
% ag 'apt install'
docs/validator/compile-and-run-a-node.md
31:    $ apt install -y git binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake gcc g++ python docker.io protobuf-compiler libssl-dev pkg-config clang llvm cargo awscli

docs/validator/validator-bootcamp.md
93:sudo apt install build-essential nodejs
197:sudo apt install -y git binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake gcc g++ python docker.io protobuf-compiler libssl-dev pkg-config clang llvm cargo
202:sudo apt install python3-pip
213:sudo apt install clang build-essential make
253:The binary path is `target/release/neard`. If you are seeing issues, it is possible that cargo command is not found. Make sure `sudo apt install cargo`. Compiling `nearcore` binary may take a little while.
538:sudo apt install python3 git curl
542:sudo apt install clang build-essential make
571:sudo apt install build-essential nodejs
724:sudo apt install ccze
993:sudo apt install curl jq
1248:sudo apt install golang-go

docs/rpc/run-rpc-node-without-nearup.md
37:    $ apt install -y git binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake gcc g++ python docker.io protobuf-compiler libssl-dev pkg-config clang llvm cargo awscli

docs/validator/running-a-node-macos-linux.md
126:apt install -y git binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake gcc g++ python docker.io protobuf-compiler libssl-dev pkg-config clang llvm
183:sudo apt install -y git binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake gcc g++ python docker.io protobuf-compiler libssl-dev pkg-config clang llvm

docs/archival/run-archival-node-without-nearup.md
37:    $ apt install -y git binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake gcc g++ python docker.io protobuf-compiler libssl-dev pkg-config clang llvm cargo awscli
```
